/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Travelling_Ticket;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Radu Adrian
 */
public class Travelling extends javax.swing.JFrame {

    /**
     * Creates new form Travelling
     */
    public Travelling() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField9 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rAdult = new javax.swing.JRadioButton();
        rStudent = new javax.swing.JRadioButton();
        rUnder = new javax.swing.JRadioButton();
        rReturn = new javax.swing.JRadioButton();
        rSingle = new javax.swing.JRadioButton();
        rStandard = new javax.swing.JRadioButton();
        rWeekend = new javax.swing.JRadioButton();
        Destination = new javax.swing.JComboBox<>();
        Tax1 = new javax.swing.JLabel();
        Under123 = new javax.swing.JLabel();
        Total1 = new javax.swing.JLabel();
        Under = new javax.swing.JTextField();
        SubTotal = new javax.swing.JTextField();
        Total = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        Subtotal1 = new javax.swing.JLabel();
        Time123 = new javax.swing.JLabel();
        Ticket123 = new javax.swing.JLabel();
        Adult123 = new javax.swing.JLabel();
        Tax = new javax.swing.JTextField();
        Time = new javax.swing.JTextField();
        Class1 = new javax.swing.JTextField();
        Adult = new javax.swing.JTextField();
        Student123 = new javax.swing.JLabel();
        Student = new javax.swing.JTextField();
        Class123 = new javax.swing.JLabel();
        Route123 = new javax.swing.JLabel();
        To123 = new javax.swing.JLabel();
        Date123 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        Route = new javax.swing.JTextField();
        To = new javax.swing.JTextField();
        Date = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        From123 = new javax.swing.JLabel();
        TicketNo123 = new javax.swing.JLabel();
        Price123 = new javax.swing.JLabel();
        From = new javax.swing.JTextField();
        TicketNo = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        Ticket1 = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Underground Ticket System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 790, 60));

        jLabel2.setText("Ticket Type");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 90, 50));

        rAdult.setText("Adult");
        rAdult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAdultActionPerformed(evt);
            }
        });
        getContentPane().add(rAdult, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        rStudent.setText("Student");
        rStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rStudentActionPerformed(evt);
            }
        });
        getContentPane().add(rStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        rUnder.setText("Under16");
        getContentPane().add(rUnder, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        rReturn.setText("Return Ticket");
        getContentPane().add(rReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        rSingle.setText("Single");
        getContentPane().add(rSingle, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        rStandard.setText("Standard");
        getContentPane().add(rStandard, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        rWeekend.setText("Weekend-50% off");
        rWeekend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rWeekendActionPerformed(evt);
            }
        });
        getContentPane().add(rWeekend, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        Destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Destination", "Edgware", "Morden", "Ealing", "Stratford" }));
        Destination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinationActionPerformed(evt);
            }
        });
        getContentPane().add(Destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 200, -1));

        Tax1.setText("Tax");
        getContentPane().add(Tax1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        Under123.setText("Under 16");
        getContentPane().add(Under123, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 160, -1, -1));

        Total1.setText("Total");
        getContentPane().add(Total1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));
        getContentPane().add(Under, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 190, 60, -1));
        getContentPane().add(SubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 110, -1));
        getContentPane().add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 110, -1));

        jButton1.setText("Total");
        jButton1.setToolTipText("Total Amount");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, -1, -1));

        Reset.setText("Reset");
        Reset.setToolTipText("Reset ");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        getContentPane().add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, -1, -1));

        Exit.setText("Exit");
        Exit.setToolTipText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 540, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 480, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 352, 490, 20));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 140, 10, 530));

        Subtotal1.setText("Subtotal");
        getContentPane().add(Subtotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 40, -1));

        Time123.setText("Time");
        getContentPane().add(Time123, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, -1, -1));

        Ticket123.setText("Ticket");
        getContentPane().add(Ticket123, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, -1, -1));

        Adult123.setText("Adult");
        getContentPane().add(Adult123, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, -1, -1));
        getContentPane().add(Tax, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 110, -1));

        Time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeActionPerformed(evt);
            }
        });
        getContentPane().add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 110, -1));
        getContentPane().add(Class1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 60, -1));

        Adult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdultActionPerformed(evt);
            }
        });
        getContentPane().add(Adult, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 60, -1));

        Student123.setText("Student");
        getContentPane().add(Student123, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, -1, -1));
        getContentPane().add(Student, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 60, -1));

        Class123.setText("Class");
        getContentPane().add(Class123, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

        Route123.setText("Route");
        getContentPane().add(Route123, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, -1, -1));

        To123.setText("To");
        getContentPane().add(To123, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, -1, -1));

        Date123.setText("Date");
        getContentPane().add(Date123, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, -1, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 290, 10));

        Route.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RouteActionPerformed(evt);
            }
        });
        getContentPane().add(Route, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 420, 110, -1));
        getContentPane().add(To, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 110, -1));
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 110, -1));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 20, 230));

        From123.setText("From");
        getContentPane().add(From123, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, -1, -1));

        TicketNo123.setText("Ticket No");
        getContentPane().add(TicketNo123, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, -1, -1));

        Price123.setText("Price");
        getContentPane().add(Price123, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, -1, -1));

        From.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromActionPerformed(evt);
            }
        });
        getContentPane().add(From, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 110, -1));
        getContentPane().add(TicketNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 110, -1));
        getContentPane().add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, 110, -1));
        getContentPane().add(Ticket1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 70, -1));

        menuBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuBar.setAutoscrolls(true);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void rAdultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAdultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rAdultActionPerformed

    private void rStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rStudentActionPerformed

    private void rWeekendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rWeekendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rWeekendActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
       
            System.exit(0); 
        
    }//GEN-LAST:event_ExitActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        Tax.setText(null);
        SubTotal.setText(null);
        Total.setText(null);
        Under.setText(null);
        Time.setText(null);
        Class1.setText(null);
        Adult.setText(null);
        Student.setText(null);
        Route.setText(null);
        To.setText(null);
        Date.setText(null);
        From.setText(null);
        TicketNo.setText(null);
        Price.setText(null);
        Ticket1.setText(null);
        
        rAdult.setSelected(false);
        rStudent.setSelected(false);
        rUnder.setSelected(false);
        rStandard.setSelected(false);
        rWeekend.setSelected(false);
        Destination.setSelectedItem("Destination");
        rSingle.setSelected(false);
        rReturn.setSelected(false);
        
    }//GEN-LAST:event_ResetActionPerformed

    private void AdultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdultActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH-mm-ss");
        Time.setText(tTime.format(timer.getTime()));
        
        SimpleDateFormat tDate = new SimpleDateFormat("dd-MM-yyyy");
        Date.setText(tDate.format(timer.getTime()));
        
        From.setText("Croydon *");
        To.setText((String) Destination.getSelectedItem() + " *");
        
        int num1;
        String q1 ="";
        num1 = 1222 + (int) (Math.random()*4238);
        q1 += num1 + 1222;
        TicketNo.setText(q1);
        
        Route.setText("Any");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void FromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromActionPerformed
        // TODO add your handling code here:
        From.setText("Croydon *");
    }//GEN-LAST:event_FromActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        double tax = 10.50;
        double M1 = 26.50;
        double M2 = 35.50;
        double M3 = 15.30;
        double M4 = 17.30;
        double M5 = 20.50;
        double M6 = 23.50;
        double M7 = 10.50;
        double M8 = 12.50;
        double M9 = 17.50;
        double M10 = 19.50;
        double M11 = 8.50;
        double M12 = 9.70;
        
        double totalCost, eco = 3.15, fclass = 5.30;
        
        if((rStandard.isSelected()) && (rSingle.isSelected()) && (rAdult.isSelected()) && Destination.getSelectedItem().equals("Edgware"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M1);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M1 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("ONE");
            Student.setText("NONE");
            Under.setText("NONE");
            
            
        }
        else if((rStandard.isSelected()) && (rSingle.isSelected()) && (rAdult.isSelected()) && Destination.getSelectedItem().equals("Morden"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M1);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M1 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("ONE");
            Student.setText("NONE");
            Under.setText("NONE");
            
            
        }
        else if((rStandard.isSelected()) && (rSingle.isSelected()) && (rAdult.isSelected()) && Destination.getSelectedItem().equals("Ealing"))
        {
            totalCost = (tax * M3) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M1);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M1 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("ONE");
            Student.setText("NONE");
            Under.setText("NONE");
            
            
        }
        else if((rStandard.isSelected()) && (rSingle.isSelected()) && (rAdult.isSelected()) && Destination.getSelectedItem().equals("Stratford"))
        {
            totalCost = (tax * M3) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M1);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M1 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("ONE");
            Student.setText("NONE");
            Under.setText("NONE");
            }
         else if((rStandard.isSelected()) && (rReturn.isSelected()) && (rAdult.isSelected()) && Destination.getSelectedItem().equals("Ealing"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M2);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M2 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("ONE");
            Student.setText("NONE");
            Under.setText("NONE");
            }
         else if((rStandard.isSelected()) && (rReturn.isSelected()) && (rAdult.isSelected()) && Destination.getSelectedItem().equals("Morden"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M2);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M2 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("ONE");
            Student.setText("NONE");
            Under.setText("NONE");
            }
         else if((rStandard.isSelected()) && (rReturn.isSelected()) && (rAdult.isSelected()) && Destination.getSelectedItem().equals("Edgware"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M2);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M2 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("ONE");
            Student.setText("NONE");
            Under.setText("NONE");
            }
        else if((rStandard.isSelected()) && (rReturn.isSelected()) && (rAdult.isSelected()) && Destination.getSelectedItem().equals("Stratford"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M2);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M2 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("ONE");
            Student.setText("NONE");
            Under.setText("NONE");
            }
        else if((rWeekend.isSelected()) && (rReturn.isSelected()) && (rAdult.isSelected()) && Destination.getSelectedItem().equals("Edgware"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M4);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M4 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("ONE");
            Student.setText("NONE");
            Under.setText("NONE");
            }
        else if((rWeekend.isSelected()) && (rReturn.isSelected()) && (rAdult.isSelected()) && Destination.getSelectedItem().equals("Stratford"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M4);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M4 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("ONE");
            Student.setText("NONE");
            Under.setText("NONE");
            }
        else if((rWeekend.isSelected()) && (rReturn.isSelected()) && (rAdult.isSelected()) && Destination.getSelectedItem().equals("Morden"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M4);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M4 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("ONE");
            Student.setText("NONE");
            Under.setText("NONE");
            }
        else if((rWeekend.isSelected()) && (rReturn.isSelected()) && (rAdult.isSelected()) && Destination.getSelectedItem().equals("Ealing"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M4);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M4 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("ONE");
            Student.setText("NONE");
            Under.setText("NONE");
            }
        else if((rWeekend.isSelected()) && (rSingle.isSelected()) && (rAdult.isSelected()) && Destination.getSelectedItem().equals("Ealing"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M3);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M3 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("ONE");
            Student.setText("NONE");
            Under.setText("NONE");
            }
        else if((rWeekend.isSelected()) && (rSingle.isSelected()) && (rAdult.isSelected()) && Destination.getSelectedItem().equals("Edgware"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M3);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M3 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("ONE");
            Student.setText("NONE");
            Under.setText("NONE");
            }
        else if((rWeekend.isSelected()) && (rSingle.isSelected()) && (rAdult.isSelected()) && Destination.getSelectedItem().equals("Morden"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M3);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M3 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("ONE");
            Student.setText("NONE");
            Under.setText("NONE");
            }
        else if((rWeekend.isSelected()) && (rSingle.isSelected()) && (rAdult.isSelected()) && Destination.getSelectedItem().equals("Stratford"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M3);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M3 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("ONE");
            Student.setText("NONE");
            Under.setText("NONE");
            }
        else if((rStandard.isSelected()) && (rSingle.isSelected()) && (rStudent.isSelected()) && Destination.getSelectedItem().equals("Stratford"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M5);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M5 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("ONE");
            Under.setText("NONE");
            }
        else if((rStandard.isSelected()) && (rSingle.isSelected()) && (rStudent.isSelected()) && Destination.getSelectedItem().equals("Ealing"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M5);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M5 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("ONE");
            Under.setText("NONE");
            }
        else if((rStandard.isSelected()) && (rSingle.isSelected()) && (rStudent.isSelected()) && Destination.getSelectedItem().equals("Morden"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M5);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M5 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("ONE");
            Under.setText("NONE");
            }
        else if((rStandard.isSelected()) && (rSingle.isSelected()) && (rStudent.isSelected()) && Destination.getSelectedItem().equals("Edgware"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M5);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M5 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("ONE");
            Under.setText("NONE");
            }
        else if((rStandard.isSelected()) && (rReturn.isSelected()) && (rStudent.isSelected()) && Destination.getSelectedItem().equals("Edgware"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M6);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M6 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("ONE");
            Under.setText("NONE");
            }
        else if((rStandard.isSelected()) && (rReturn.isSelected()) && (rStudent.isSelected()) && Destination.getSelectedItem().equals("Ealing"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M6);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M6 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("ONE");
            Under.setText("NONE");
            }
        else if((rStandard.isSelected()) && (rReturn.isSelected()) && (rStudent.isSelected()) && Destination.getSelectedItem().equals("Stratford"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M6);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M6 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("ONE");
            Under.setText("NONE");
            }
        else if((rStandard.isSelected()) && (rReturn.isSelected()) && (rStudent.isSelected()) && Destination.getSelectedItem().equals("Morden"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M6);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M6 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("ONE");
            Under.setText("NONE");
            }
        else if((rWeekend.isSelected()) && (rSingle.isSelected()) && (rStudent.isSelected()) && Destination.getSelectedItem().equals("Morden"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M7);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M7 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("ONE");
            Under.setText("NONE");
            }
         else if((rWeekend.isSelected()) && (rSingle.isSelected()) && (rStudent.isSelected()) && Destination.getSelectedItem().equals("Edgware"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M7);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M7 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("ONE");
            Under.setText("NONE");
            }
         else if((rWeekend.isSelected()) && (rSingle.isSelected()) && (rStudent.isSelected()) && Destination.getSelectedItem().equals("Stratford"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M7);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M7 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("ONE");
            Under.setText("NONE");
            }
         else if((rWeekend.isSelected()) && (rSingle.isSelected()) && (rStudent.isSelected()) && Destination.getSelectedItem().equals("Ealing"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M7);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M7 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("ONE");
            Under.setText("NONE");
            }
        else if((rWeekend.isSelected()) && (rReturn.isSelected()) && (rStudent.isSelected()) && Destination.getSelectedItem().equals("Ealing"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M8);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M8 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("ONE");
            Under.setText("NONE");
            }
         else if((rWeekend.isSelected()) && (rReturn.isSelected()) && (rStudent.isSelected()) && Destination.getSelectedItem().equals("Edgware"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M8);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M8 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("ONE");
            Under.setText("NONE");
            }
         else if((rWeekend.isSelected()) && (rReturn.isSelected()) && (rStudent.isSelected()) && Destination.getSelectedItem().equals("Stratford"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M8);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M8 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("ONE");
            Under.setText("NONE");
            }
         else if((rWeekend.isSelected()) && (rReturn.isSelected()) && (rStudent.isSelected()) && Destination.getSelectedItem().equals("Morden"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M8);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M8 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("ONE");
            Under.setText("NONE");
            }
         else if((rStandard.isSelected()) && (rSingle.isSelected()) && (rUnder.isSelected()) && Destination.getSelectedItem().equals("Morden"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M9);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M9 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("NONE");
            Under.setText("ONE");
            }
        else if((rStandard.isSelected()) && (rSingle.isSelected()) && (rUnder.isSelected()) && Destination.getSelectedItem().equals("Edgware"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M9);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M9 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("NONE");
            Under.setText("ONE");
            }
        else if((rStandard.isSelected()) && (rSingle.isSelected()) && (rUnder.isSelected()) && Destination.getSelectedItem().equals("Stratford"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M9);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M9 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("NONE");
            Under.setText("ONE");
            }
        else if((rStandard.isSelected()) && (rSingle.isSelected()) && (rUnder.isSelected()) && Destination.getSelectedItem().equals("Ealing"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M9);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M9 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("NONE");
            Under.setText("ONE");
            }
        else if((rStandard.isSelected()) && (rReturn.isSelected()) && (rUnder.isSelected()) && Destination.getSelectedItem().equals("Ealing"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M10);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M10 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("NONE");
            Under.setText("ONE");
            }
        else if((rStandard.isSelected()) && (rReturn.isSelected()) && (rUnder.isSelected()) && Destination.getSelectedItem().equals("Stratford"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M10);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M10 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("NONE");
            Under.setText("ONE");
            }
        else if((rStandard.isSelected()) && (rReturn.isSelected()) && (rUnder.isSelected()) && Destination.getSelectedItem().equals("Morden"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M10);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M10 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("NONE");
            Under.setText("ONE");
            }
        else if((rStandard.isSelected()) && (rReturn.isSelected()) && (rUnder.isSelected()) && Destination.getSelectedItem().equals("Edgware"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M10);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M10 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("NONE");
            Under.setText("ONE");
            }
        else if((rWeekend.isSelected()) && (rSingle.isSelected()) && (rUnder.isSelected()) && Destination.getSelectedItem().equals("Edgware"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M11);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M11 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("NONE");
            Under.setText("ONE");
            }
        else if((rWeekend.isSelected()) && (rSingle.isSelected()) && (rUnder.isSelected()) && Destination.getSelectedItem().equals("Morden"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M11);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M11 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("NONE");
            Under.setText("ONE");
            }
        else if((rWeekend.isSelected()) && (rSingle.isSelected()) && (rUnder.isSelected()) && Destination.getSelectedItem().equals("Stratford"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M11);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M11 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("NONE");
            Under.setText("ONE");
            }
        else if((rWeekend.isSelected()) && (rSingle.isSelected()) && (rUnder.isSelected()) && Destination.getSelectedItem().equals("Ealing"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M11);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M11 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("NONE");
            Under.setText("ONE");
            }
         else if((rWeekend.isSelected()) && (rReturn.isSelected()) && (rUnder.isSelected()) && Destination.getSelectedItem().equals("Ealing"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M12);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M12 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("NONE");
            Under.setText("ONE");
            }
        else if((rWeekend.isSelected()) && (rReturn.isSelected()) && (rUnder.isSelected()) && Destination.getSelectedItem().equals("Morden"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M12);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M12 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("NONE");
            Under.setText("ONE");
            }
        else if((rWeekend.isSelected()) && (rReturn.isSelected()) && (rUnder.isSelected()) && Destination.getSelectedItem().equals("Stratford"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M12);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M12 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("NONE");
            Under.setText("ONE");
            }
        else if((rWeekend.isSelected()) && (rReturn.isSelected()) && (rUnder.isSelected()) && Destination.getSelectedItem().equals("Edgware"))
        {
            totalCost = (tax * M1) / 100;
            String sTax = String.format("£%.2f",totalCost);
            Tax.setText(sTax);
            String subTotal = String.format("£%.2f",M12);
            SubTotal.setText(subTotal);
            String total = String.format("£%.2f",M12 + totalCost);
            Total.setText(total);
            Price.setText(total);
            Class1.setText("Normal");
            Ticket1.setText("ONE WAY");
            Adult.setText("NONE");
            Student.setText("NONE");
            Under.setText("ONE");
            }
    }//GEN-LAST:event_jButton1MouseClicked

    private void DestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DestinationActionPerformed

    private void TimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeActionPerformed

    private void RouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RouteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RouteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Travelling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Travelling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Travelling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Travelling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Travelling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Adult;
    private javax.swing.JLabel Adult123;
    private javax.swing.JTextField Class1;
    private javax.swing.JLabel Class123;
    private javax.swing.JTextField Date;
    private javax.swing.JLabel Date123;
    private javax.swing.JComboBox<String> Destination;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField From;
    private javax.swing.JLabel From123;
    private javax.swing.JTextField Price;
    private javax.swing.JLabel Price123;
    public javax.swing.JButton Reset;
    private javax.swing.JTextField Route;
    private javax.swing.JLabel Route123;
    private javax.swing.JTextField Student;
    private javax.swing.JLabel Student123;
    private javax.swing.JTextField SubTotal;
    private javax.swing.JLabel Subtotal1;
    private javax.swing.JTextField Tax;
    private javax.swing.JLabel Tax1;
    private javax.swing.JTextField Ticket1;
    private javax.swing.JLabel Ticket123;
    private javax.swing.JTextField TicketNo;
    private javax.swing.JLabel TicketNo123;
    private javax.swing.JTextField Time;
    private javax.swing.JLabel Time123;
    private javax.swing.JTextField To;
    private javax.swing.JLabel To123;
    private javax.swing.JTextField Total;
    private javax.swing.JLabel Total1;
    private javax.swing.JTextField Under;
    private javax.swing.JLabel Under123;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JRadioButton rAdult;
    private javax.swing.JRadioButton rReturn;
    private javax.swing.JRadioButton rSingle;
    private javax.swing.JRadioButton rStandard;
    private javax.swing.JRadioButton rStudent;
    private javax.swing.JRadioButton rUnder;
    private javax.swing.JRadioButton rWeekend;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
